---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.rabbitmq.name }}
spec:
  selector:
    matchLabels:
      app:  {{ .Values.rabbitmq.app }}
  replicas: {{ .Values.rabbitmq.replicaCount }}
  template:
    metadata:
      labels:
        app: {{ .Values.rabbitmq.app }}
    spec:
      containers:
      - image: "{{ .Values.rabbitmq.image}}:{{ .Values.rabbitmq.tag}}"
        resources:
            {{- if and .Values.rabbitmq.limits_memory .Values.rabbitmq.limits_cpu .Values.rabbitmq.requests_memory .Values.rabbitmq.requests_cpu -}}
            limits:
              memory: {{ .Values.rabbitmq.limits_memory }}
              cpu: {{ .Values.rabbitmq.limits_cpu }}
            requests:
              memory: {{ .Values.rabbitmq.requests_memory }}
              cpu: {{ .Values.rabbitmq.requests_cpu }}
            {{- else -}}
            {}
            {{- end -}}
        imagePullPolicy: {{ .Values.rabbitmq.imagePullPolicy}}
        name:  {{ .Values.rabbitmq.name }}
        ports:
        - containerPort: 5672
        
---
apiVersion: v1
kind: Service
metadata:
  name:  {{ .Values.rabbitmq.name }}
spec:
  ports:
    - port: 5672
      targetPort: 5672
      protocol: TCP
  type: ClusterIP
  selector:
    app: {{ .Values.rabbitmq.app }}
---